apiVersion: v1
kind: Service
metadata:
  name: opentsdb-svc
spec:
  selector:
    app: opentsdb
  ports:
    - name: port1
      port: 4242
      targetPort: 4242
---
apiVersion: v1
kind: Pod
metadata:
    name: opentsdb
    labels:
      app: opentsdb
spec:
  containers:
    - name: opentsdb-node
      image: index.caicloud.io/caicloud/opentsdb
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 4242
        name: port1
